### ISSUE TITLE
Position Legend View

### ISSUE THREAD

**Issue by kam56** [ItJustWorksBetterTM/EiffelVis#1]
As a user I want the legend view to be displayed by default on the top left so I can remind myself of what I’m looking at.

**Acceptance Criteria**

- [x] The Legend is displayed on the top left of the page on load. 
- [x] The legend can be minimised on request.
- [x] Follow the accepted prototype design
- [x] Design should match the current style of the frontend
- [x] Code is commented
- [x] Testing - Check whether the legend is displayed on page load

**Comment by alrapal** [comment]
This has been implemented with #21
