### ISSUE TITLE
3D graph

### ISSUE THREAD

**Issue by kam56** [ItJustWorksBetterTM/EiffelVis#11]
As a user, I want to be able to swap the graph from 2D to 3D at any time in order to gain valuable perspective. (WOW)

**Acceptance Criteria**

- [ ] The graph is toggleable from 2D to 3D.
- [ ] The 3D graph is optimized enough to not cause software hiccups.

**Comment by RuthgerD** [comment]
Any idea what technology will drive this?

**Comment by alrapal** [comment]
This will not be doable with given time and we have decided to discard it.
