### ISSUE TITLE
Plans for upstreaming improvements?

### ISSUE THREAD

**Issue by RuthgerD** [ItJustWorksBetterTM/EiffelVis#12]
As title says, as i understand plans are to improve the frontend (which I agree wasn't the focus for us) and I think it would be great as both an exercise and for the greater good to eventually submit the work for review.

We at ItJustWorks would be happy to spend some time accommodating that.

**Comment by ktpa** [comment]
Hello ItJustWorks,

We appreciate your input on our development journey and as you have guessed our primary focus will be to improve the frontend. While we can put down a lot of things in text we think that a meeting would be a great way to start our communication. Do you agree? Perhaps we can find a time on Zoom this week even? Let us know.

K

**Comment by RuthgerD** [comment]
The team here will keep their own master / devel, and then hope to cherry pick + PR things that are deemed ready.
