### ISSUE TITLE
Identify Legend Items on a type-bases

### ISSUE THREAD

**Issue by kam56** [ItJustWorksBetterTM/EiffelVis#2]
As a user I want the legend items to be uniquely identified on a type-basis so that I can easily distinguish between them.

**Acceptance Criteria**

- [x] Follow the accepted prototype design.
- [x] Colours should be easy to read and visually pleasing as well as meeting the acceptance criteria of US6.
- [x] Design should match the current style of the frontend.
- [x] Legend items should be distinguished by colour and shape.
- [ ] Code is commented.

**Comment by alrapal** [comment]
Changed this to include #3 as decided during mid sprint planning
