### ISSUE TITLE
Hide filter panel

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksBetterTM/EiffelVis#33]
## Description
As a user, I want to be able to hide the filter panel so that I can have full use of the screen to look at the graph

## Acceptance criteria
- [x] The performance is not downgraded
- [x] Filter button should be placed alongside the other buttons on the side panel
- [x] Button should indicate that it is a filter icon for easy understanding
- [x] The design should follow the overall prototype
- [x] Code should be commented
- [x] Code is proper typescript with type definitions for everything

**Comment by kam56** [comment]
Related up-stream PR: https://github.com/ItJustWorksTM/EiffelVis/pull/145

The PR is merged, therefore this issue must be closed.
