### ISSUE TITLE
Rework of app design

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksBetterTM/EiffelVis#34]
## Description
App should be reworked following this [prototype](https://www.figma.com/proto/nUvQFcBLjBwBXy55isFmrn/Eiffelvis_prototype_web?page-id=65%3A134&node-id=157%3A114&starting-point-node-id=157%3A114&show-proto-sidebar=1)

## Acceptance criteria
- [ ] Code is commented
- [ ] Code uses typescript
- [ ] Result presents the prototyped design
- [ ] Legend can be a placeholder
- [ ] Page should stay responsive (For bigger screen mostly)

**Comment by RuthgerD** [comment]
is this prototype final?
here's some feedback:
the left sidebar looks nice but it will permanently take up space, which was the original reason of making it floating on the right
Putting the event legend on the top left feels awkward, feels unfinished
Stacking the graph options onto the filter panel makes it very crowded with information

**Comment by alrapal** [comment]
> is this prototype final?
> here's some feedback:
> the left sidebar looks nice but it will permanently take up space, which was the original reason of making it floating on the right
> Putting the event legend on the top left feels awkward, feels unfinished
> Stacking the graph options onto the filter panel makes it very crowded with information

We are currently working on it so it is not the final prototype with all the features implemented :) (Luckily) 

The main idea is to have that bar on the left side and be able to toggle off every panel. 
The panels would stack within the space they are allocated using a combination of cards and scroll when overflow.
The graph is currently not taking all the space it can on the left side so it would not be very different, just clearer. (Panels would float on the graph space when they are activated) 

Ideally users will not need to have all panels open (we will add more panels with the features that are coming, like for shortcuts for instance). 
We will also rework the filtering view to make it a bit more compact and clearer (without changing the overall functionning).
We think that by allowing to hide the filter view (requirement from customer), users would be able to manage how that space is crowded. And if they want to open several panels at the same time, there will be a possibility to collapse them as well as scroll in that panel column space. 

We also considered the possibility to have the slide bar sliding in and out on hover to make space for the graph but we want to talk to the customer first to see if it is something they would feel is useful or annoying (we can also make it an option eventually). 

A bit difficult to explain this through words haha! We have planned on reworking a prototype that shows in a clearer way our full intention. This one used screenshots to be able to have a base to go from which limits the ability to make an actual prototype. 
If I was unclear by any mean, we can take a moment to chat over zoom, or I can make a quick prototype just with areas to show you the intention =)

**Comment by RuthgerD** [comment]
Alright ping this issue when the prototype has evolved

**Comment by alrapal** [comment]
@Kevinayad you can post the link here when you are done with the prototype :)
