### ISSUE TITLE
Hardcoded or not?

### ISSUE THREAD

**Issue by ktpa** [ItJustWorksBetterTM/EiffelVis#52]
https://github.com/ItJustWorksBetterTM/EiffelVis/blob/8250083dc107481c917eea70d43b2e7ed38f2441/frontend/src/components/G6Graph.svelte#L238

Should the shift modification be hard coded?

**Comment by RuthgerD** [comment]
What does the modifier do?

**Comment by ktpa** [comment]
The modifier is a name that reflects that the shift button is simultaneously pressed while another key is pressed. The modification I'm referencing is number 4 which in this instance increases the graph translation by a factor of 4.

Moving this 4 to the top instead, perhaps naming it modifierStrength, will make it easier to adjust the shift key translation value.

**Comment by RuthgerD** [comment]
Never realized you could have capslock arrow keys! but it should probably be configurable yes
