### ISSUE TITLE
Improvement: element positioning on page

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksBetterTM/EiffelVis#53]
# Description
Elements are currently hard coded in their positioning which prevents the implementation of new panels (like the shortcut panel) 
- Width of the different panels needs to be consistent between each other
- Graph should be visible under the panel
- Graph should be interactive on all areas that are not covered by panels (beside gap between panels) 
- When too many panels are on screen to be displayed, it should be possible to scroll to see the hidden panels

**Comment by ktpa** [comment]
Great thoughts and suggestions, backing 100%.

**Comment by alrapal** [comment]
Addressed with #54
