### ISSUE TITLE
Keyboard shortcuts for navigating through timeline

### ISSUE THREAD

**Issue by kam56** [ItJustWorksBetterTM/EiffelVis#7]
As a user, I want to be able to navigate through the nodes by using keyboard shortcuts only, so that I can interact with the system more intuitively.

**Acceptance Criteria**

- [ ] The user can use shift and mouse left click to focus a certain node group.
- [ ] The user can use the predefined key to toggle on/off the label display.
- [ ] The user can use arrow keys to navigate the timeline.
- [ ] The available shortcuts are gathered and made accessible for the user to consult them.
- [ ] Code is proper typescript with type definitions for everything.
- [ ] Code is commented

**Comment by RuthgerD** [comment]
Is this a mockup or actual html?

**Comment by ktpa** [comment]
> A proposition of how the Shortcut panel and button could look like <img alt="Screenshot 2022-11-22 at 10 24 11" width="919" src="https://user-images.githubusercontent.com/71485862/203276265-33df4c89-a44a-4b94-b361-5778e373fc2d.png">

Should also specify that keyboard arrows can be used for vertical graph navigation as well.

**Comment by alrapal** [comment]
> Is this a mockup or actual html?

This is a mockup

> Should also specify that keyboard arrows can be used for vertical graph navigation as well.

Yes true ! I will add this

**Comment by RuthgerD** [comment]
Seems sane, will there be support to rebind these shortcuts later on? Might be something to think about.

**Comment by alrapal** [comment]
It would be something cool! Definitely something to think about later on. Depends how we want to do it (config file on build, on user interface based). 
In the latest, I think it should not be too difficult to implement if we use components for each shortcut

**Comment by RuthgerD** [comment]
The keybinds would need to be stored in the user local storage, so each user can configure it independently and without loosing the settings when refreshing the page.

**Comment by alrapal** [comment]
We could think that the 'key' is an input text (styled as a key) and can be adjusted and saved in local storage for instance.
